// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(io) {
    var VideoModel, connectCount, escape, video_sockets;
    escape = require('escape-html');
    VideoModel = require('../model/Video');
    connectCount = {
      'i0': 0
    };
    global.video_sockets = video_sockets = io.of('/video');
    video_sockets.on('connection', function(socket) {
      connectCount['i0']++;
      socket.emit('connected');
      socket.on('connected', function(data) {
        var vid, vindex;
        vid = data.id;
        vindex = 'i' + vid;
        socket.v_data = data;
        if (!connectCount[vindex]) {
          connectCount[vindex] = 0;
        }
        connectCount[vindex]++;
        video_sockets.emit('connected' + vid, {
          count: connectCount[vindex]
        });
        return socket.on('barrage' + vid, function(barrage) {
          barrage.content = escape(barrage.content);
          barrage.time = (new Date()).getTime();
          return VideoModel.addBarrage(vid, barrage, function(err) {
            return video_sockets.emit('barrage' + vid, barrage);
          });
        });
      });
      video_sockets.emit('total connection', {
        count: connectCount['i0']
      });
      socket.on('disconnect', function() {
        var vindex;
        vindex = 'i' + socket.v_data.id;
        connectCount['i0']--;
        video_sockets.emit('someone connect', {
          count: connectCount['i0']
        });
        connectCount[vindex]--;
        video_sockets.emit('connected' + socket.v_data.id, {
          count: connectCount[vindex]
        });
        socket.emit('');
      });
    });
  };

}).call(this);

//# sourceMappingURL=sockets.map
