// Generated by CoffeeScript 1.6.3
(function() {
  var path;

  path = require('path');

  global.getNextId = function(name, callback) {
    return global.db.collection('counters').findAndModify({
      _id: name
    }, [['_id', 'asc']], {
      $inc: {
        seq: 1
      }
    }, {
      "new": true
    }, callback);
  };

  global.resumable = require('./modules/resumable-node.js')(path.join(__dirname, '/temp/'));

  global.STATUS_SUCCESS = 'success';

  global.STATUS_ERROR = 'error';

  global.json_response = function(res, status, data, message, page) {
    var json;
    res.set('Content-Type', 'application/json');
    json = JSON.stringify({
      status: status,
      data: data,
      message: message,
      page: page
    });
    return res.end(json);
  };

  module.exports = global;

}).call(this);
