// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    db: 'danmu',
    host: 'localhost',
    ffmpegPath: 'E:\\ffmpeg\\bin\\ffmpeg.exe',
    cookieSecret: 'socket.io'
  };

}).call(this);
